name: CI | Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" -y
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential python3-pip clang 
        sudo apt-get install -y libspdlog-dev nlohmann-json3-dev libglm-dev
        pip3 install conan

    - name: Get Conan version
      id: conan-version
      run: echo "version=$(conan --version | grep -oP '(?<=Conan version )[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_OUTPUT
    
    - name: Cache Conan packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.conan2/p
          ~/.conan2/cache
        key: ${{ runner.os }}-conan-${{ steps.conan-version.outputs.version }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}
        restore-keys: |
          ${{ runner.os }}-conan-${{ steps.conan-version.outputs.version }}-
    
    - name: Configure Conan
      run: |
        conan --version
        conan profile detect --force

    - name: Cache CMake build
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}-
    
    - name: Build Debug
      run: |
        # Make build scripts executable
        chmod +x ./build_and_run.sh
        chmod +x ./coverage.sh
        
        # Needs to match exactly with the CMakePresets.json
        mkdir -p build/Debug
        
        ./build_and_run.sh --debug --no-run
